services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: focalpoint-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://aliqyaan12:%23Aliqyaan10@cluster0.dwqe9tr.mongodb.net/workspace
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - focalpoint-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: focalpoint-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_NODE_BASE_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - focalpoint-network

networks:
  focalpoint-network:
    driver: bridge