version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: focalpoint-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb+srv://aliqyaan12:%23Aliqyaan10@cluster0.dwqe9tr.mongodb.net/workspace
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - focalpoint-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: focalpoint-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_NODE_BASE_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - focalpoint-network

networks:
  focalpoint-network:
    driver: bridge